import { DrawingData } from "./mapDrawingMode"

export type Point = {
    x: number,
    y: number
}

export type CharacterCondition = {
    label: string,
    force: number,
    id: string
}

export type ConditionDrawingData = Rectangle & CharacterCondition & {forceX: number};

export type DrawingEditOperation = {
    ready: boolean
}

export type assetType = {
    x: number,
    y: number,
    size? : number
    graphicUrl: string,
    img?: HTMLImageElement,
    toBeRedrawn? :boolean,
    resized? :boolean,
    mouseOnMap? :boolean,
    sourceWidth?: number,
    sourceHeight?: number,
    currentGraphicUrl?: string,
    isVisible? : boolean,
    isDrawn? : boolean,
    name: string

}

export type characterType = assetType & {
    aimedX?: number,
    aimedY?: number,
    id: string,
    active?: boolean,
    speed?: number,
    currentHP?: number,
    maxHP?: number,
    conditions?: CharacterCondition[]
}

export type mapType = assetType & {
    visibleWidth: number,
    visibleHeight: number,
    canvas: CanvasRenderingContext2D,
    rawCanvas: HTMLCanvasElement,
    assets : characterType[],
    assetsHashedTable: Map<string, characterType>,
    pressedKeys: any,
    presets: mapPresets,
    mouseX :number,
    mouseY: number,
    onCanvasX: number,
    onCanvasY: number,
    borderVisible? : boolean,
    onCanvasWidth: number,
    onCanvasHeight: number,
    sourceX: number,
    sourceY: number,
    rightBorderVisible? : boolean,
    bottomBorderVisible? : boolean,
    borderImg?: HTMLImageElement,
    borderImgReady?: boolean,
    frameDrawing? : boolean,
    activeSide: number,
    controllFunction: Function,
    activeAssetId?: string,
    absoluteMouseX: number,
    absoluteMouseY: number,
    miniMapWidth?: number,
    miniMapHeight?: number,
    miniMapBorderX?: number,
    miniMapBorderY?: number,
    miniMapX?: number,
    miniMapY?: number,
    miniMapPointerWidth?: number,
    miniMapPointerHeight?: number,
    miniMapPointerX? :number,
    miniMapPointerY? :number,
    miniMapAimedX?: number,
    miniMapAimedY?: number,
    miniMapCurrentX?: number,
    miniMapCurrentY?: number,
    mouseOnMiniMap?: boolean,
    measuring: boolean,
    measurePoint: Point,
    distance: {meters: string, feets:string},
    measureFont: string,
    measureLineWidth: number,
    measureRadius: number,
    showMiniMap? :boolean,
    allowHideMiniMap? :boolean,
    placeholderFont: string,
    distanceOverflowing? :boolean,
    pinging? :boolean,
    startPing? :boolean,
    pingX? :number,
    pingY? :number,
    pingingCount? :number,
    pingDirection?: boolean,
    pingFilledRadius? :number,
    pingCutRadius? :number,
    pingVisibleOnMiniMap? :boolean,
    miniMapPingX? :number,
    miniMapPingY? :number,
    miniMapPingRadius? :number,
    isContextMenuOpened? :boolean,
    choosenContextMenu?: rightClickMenuType,
    contextMenuWidth? :number,
    contextMenuHeight? :number,
    contextMenuX? :number,
    contextMenuY? :number,
    contextMargin: number,
    contextItemsDistance: number,
    contextExtraDownMargin: number,
    contextMenuFontSize: number,
    contextMenuFontName: string,
    contextMenuBackgroundColor: string,
    contextMenuTextColor: string,
    contextMenuBackgroundColorHover: string,
    contextMenuTextColorHover: string,
    contextMenuBorderColor: string,
    contexMenuFontStyle? :string,
    contextMenuItemHeight: number,
    selectedContextMenuItem?: number,
    contextMenuMinWidth :number,

    drawingModeMaxSize: number,
    drawingModeMinSize: number,
    drawingModeMaxAngle: number,
    drawingModeMinAngle: number,
    lastPointOfMouseDown : Point,

    editingDrawing: DrawingData, 
    drawingSelectionRectangle?: Rectangle,

    editingDrawingOperation?: '' | 'resizing' | 'rotating' | 'moving',
    drawingResizng: DrawingEditOperation & {initialPoint: Point, initialDistance: number, initialSize: number, currentPoint: Point},
    drawingRotating: DrawingEditOperation & {referencePoint: Point, previousPoint: Point, initialAngle: number},
    drawingMoving: DrawingEditOperation;
    newDrawingInProgress? :boolean
    drawingHasChanged?: boolean,
    drawingSelected?: boolean,
    lastMouseDownTime: number,

    drawnShapes : shapesDrawnByUser[],
    currentAssetHP?: number
    maxAssetHP?: number
    HPBarX: number,
    HPBarY: number,
    HPBarFilledWidth: number,
    HPBarWrapperWidth: number,
    HPBarText: string,
    HPBarTextX: number,
    deadAssetImage: characterType,

    HoveredCharacterConditions?: ConditionDrawingData[],
    currentlyHoverAssetID?: string,

    inititiveCashedFromServer?: InitativeFromServer, 
    initiative: characterType[],
    initiativeElementsToMoveDown: characterType[],
    initiativeElementsToMoveLeft: characterType[],
    initiativeAnimationStage: number,
    initiativeAnimationDistanceX: number,
    initiativeLeftDecorator: characterType,
    initiativeRightDecorator: characterType,
    initiativeLeftDecoratorX?: number,
    initiativeRightDecoratorX?: number,

    fancyBorder: characterType,
    // characterInititativeBorder: characterType
}

export type rightClickMenuType = {label:string, event: Function}[]

type InitativeFromServer = {
    queue: {id: string, name: string}[],
    currentID: string
}


 type shapesDrawnByUser = {
    userName: string,
    shapes: DrawingData[]
}

type Rectangle = {
    x: number,
    y: number,
    width: number,
    height: number
}

export function getDefaultMap(canvasContext: CanvasRenderingContext2D, canvas: HTMLCanvasElement, presets:mapPresets, externalFunction: Function){
    const returned : mapType = {

        canvas: canvasContext,
        rawCanvas: canvas,
        assets: [],
        assetsHashedTable: new Map(),
        x: 0,
        y: 0,
        sourceWidth: 0,
        sourceHeight: 0,
        visibleWidth: 0,
        visibleHeight: 0,
        graphicUrl: 'https://s13.gifyu.com/images/S0Irz.jpg',
        currentGraphicUrl: '',
        toBeRedrawn: true,
        presets: presets,
        mouseX :0,
        mouseY :0,
        pressedKeys: {},
        onCanvasX: 0,
        onCanvasY: 0,
        onCanvasWidth: 0,
        onCanvasHeight: 0,
        sourceX: 0,
        sourceY: 0,
        activeSide: 0,
        controllFunction: externalFunction,
        absoluteMouseX: 0,
        absoluteMouseY: 0,
        measuring: false,
        measurePoint: {x:0, y:0},
        distance: {meters:'', feets:''},
        measureFont: '30px Laila',
        measureLineWidth: 5,
        measureRadius: 0,
        showMiniMap: true,
        allowHideMiniMap: true,
        placeholderFont: '30px Fondamento',
        name: 'placeholder-name',
        contextMargin: 10,
        contextItemsDistance: 5,
        contextMenuFontSize: 15,
        contextExtraDownMargin: 10,
        contextMenuFontName: 'Fondamento',
        contextMenuBackgroundColor: '#493f32',
        contextMenuTextColor: '#bca45c',
        contextMenuBackgroundColorHover: '#771a0e',
        contextMenuTextColorHover: '#d8bb66',
        contextMenuItemHeight: 0,
        contextMenuMinWidth: 100,
        // contextMenuTextColorHover: '#f00',

        contextMenuBorderColor: '#372e24',
        drawingModeMaxSize: 1000,
        drawingModeMinSize: 10,
        drawingModeMaxAngle: 359,
        drawingModeMinAngle: 0,        
        drawnShapes: [],
        editingDrawing: getDefaultDrawing(),
        lastPointOfMouseDown: {x: 0, y: 0},
        lastMouseDownTime: 0,

        HPBarX: 0,
        HPBarY: 0,
        HPBarFilledWidth: 0,
        HPBarWrapperWidth: 0,
        HPBarText: '',
        HPBarTextX: 0,
        deadAssetImage: {x: 0, y: 0, name: 'dead', graphicUrl: 'https://s14.gifyu.com/images/bN2h7.webp', id: '2137694201213'},

        drawingResizng: {ready: false, initialPoint: {x:0, y:0}, initialDistance:0, initialSize: 0, currentPoint:{x:0,y:0}},
        drawingRotating: {ready: false, referencePoint: {x:0, y:0}, previousPoint: {x:0, y:0}, initialAngle: 0},
        drawingMoving: {ready: false},
        initiative: [],
        initiativeElementsToMoveDown: [],
        initiativeElementsToMoveLeft: [],
        initiativeAnimationStage: 0,
        initiativeAnimationDistanceX: 0,
        initiativeLeftDecorator:  {x: 0, y: 0, graphicUrl: 'https://s14.gifyu.com/images/bTxTW.png', name: 'ini-left', id: 'ini-left'},
        initiativeRightDecorator: {x: 0, y: 0, graphicUrl: 'https://s14.gifyu.com/images/bTxTQ.png', name: 'ini-rigth', id: 'ini-right'},
        fancyBorder: {x: 0, y: 0, graphicUrl: 'https://s14.gifyu.com/images/bTpmJ.webp', name: 'fancyBorder', id: 'fancyBorder'},
        // characterInititativeBorder: {x: 0, y: 0, graphicUrl: 'https://s14.gifyu.com/images/bTLyk.webp', name: 'ini-border', id: 'ini-border'},
    }

    return returned;
}

export type mapPresets = {
    ASSET_SIZE : number,
    PRIMARY_SCROLL_KEY : string,
    SECONDARY_SCROLL_KEY : string,
    DISABLE_MINI_MAP_KEY : string,     
    START_MEASURE_KEY: string, //lowerCase!!!
    STOP_MEASURE_KEY: string,   //lowerCase!!!
    MINI_MAP_HEIGHT_PERCENT?: number,
    MINI_MAP_WIDTH_PERCENT?: number,
    MAP_WIDTH_PERCENT: number,
    MAP_HEIGHT_PERCENT: number,
    MAP_BORDER_LENGTH: number,
    SCROLLING_SPEED: number,
    SCROLLING_BOOSTER: number,
    SCROLL_MOUSE_POSITION_THRESHOLD: number //0-1,
    POSITION_X_ON_CANVAS: number,
    POSITION_Y_ON_CANVAS: number,
    MAP_BORDER_COLOR: string,
    BORDER_GRAPHIC_URL: string,
    ASSET_STEP_SIZE: number,
    ASSET_ACTIVE_STROKE_STYLE: string,
    ASSET_ACTIVE_LINE_WIDTH: number,
    ASSET_ACTIVE_SHADOW_FILL_STYLE: string,
    PLACEHOLDER_TEXT : string,
    DISTANCE_TEXT_SIZE_PERCENT: number,
    PLAHOLDER_FILL_STYLE : string,
    PLACEHOLDER_TEXT_ALIGNMENT: 'start' | 'end' | 'center' | 'left' | 'right',
    PLACEHOLDER_FONT: string,
    PLACEHOLDER_TEXT_SIZE_PERCENT: number,
    MINI_MAP_RIGHT_MARGIN_PERCENT?: number,
    MINI_MAP_BOTTOM_MARGIN_PERCENT?: number,
    MINI_MAP_BORDER_THICKNESS?: number,
    MINI_MAP_BORDER_STROKE_STYLE? :string,
    MINI_MAP_POINTER_FILL_STYLE? : string,
    MINI_MAP_PREVIEW_STROKE_STYLE? :string,
    MINI_MAP_PREVIEW_LINE_WIDTH?: number,
    FEET_DISTANCE_MULTIPLIER: number,
    DISTANCE_FONT: string,
    DISTANCE_FONT_SIZE_PERCENT: number,
    DISTANCE_LINE_COLOR: string,
    DISTANCE_CIRCLE_FILL_STYLE: string,
    DISTANCE_LINE_WIDTH_PERCENT: number,
    DISTANCE_FONT_FILL_STYLE: string,
    DISTANCE_OVERFLOWING_FONT_FILL_STYLE: string,
    DISTANCE_FONT_STROKE_STYLE: string,
    DISTANCE_OVERFLOWING_FONT_STROKE_STYLE: string,
    DISTANCE_OVERFLOWING_LINE_COLOR: string,
    MINI_MAP_HIDE_FILTER_TIME?: number,
    PING_TIME_MILISECONDS: number,
    PING_MINIMAL_RADIUS: number,
    PING_MAXIMAL_RADIUS: number,
    PING_INCREASE_RADIUS: number,
    PING_MAX_NUMBER_OF_CYCLES: number,
    PING_FILL_STYLE: string,
    PING_MINI_MAP_COLOR: string,
    HP_BAR_Y: number,
    HP_BAR_HEIGHT: number,
    HP_BAR_BORDER_COLOR: string,
    HP_BAR_COLOR: string,
    HP_BAR_EMPTY_COLOR: string,
    HP_BAR_TEXT_COLOR: string,
    HP_BAR_FONT: string
    HP_BAR_BORDER_THICKNESS: number,
    HP_BAR_TOP_MARGIN: number,
    HP_BAR_TEXT_OFFSET_Y: number,
    HP_BAR_WIDTH_OVERFLOW: number,
    HP_BAR_TEXT_ALIGN: 'start' | 'end' | 'center' | 'left' | 'right',
    COORDINATES_BOX_X: number,
    COORDINATES_BOX_Y: number,
    COORDINATES_TEXT_FONT: string,
    MOUSE_CLICK_TIME_FILTER: number,
    SIZE_INCREASE_FILTER: number,
    DRAWING_MAX_SIZE: number,
    DRAWING_MIN_SIZE: number,
    PREVENT_SELECTING_CHARACTERS_KEY: string,
    MAX_CONDITIONS_PER_ROW: number,
    CONDITION_FONT: string,
    CONDITION_GRID_GAP: number,
    CONDITION_PADDING: number,
    CONDITION_BORDER_WIDTH: number,
    DISTANCE_BEFORE_CONDITION_FORCE: number,
    CONDITIONS_MARGIN_TOP: number,

    INITIATIVE_MAX_WIDTH_PERCENTAGE : number,
    INITIATIVE_DECORATOR_WIDTH: number,
    INITIATIVE_DECORATOR_HEIGHT: number,
    INITIATIVE_PADDING: number,
    INITIATIVE_ASSET_SIZE: number,
    INITIATIVE_DISTANCE_BETWEEN_ASSETS: number,
    INITIATIVE_Y_POSITION: number
}

export function getMainMapPresets(){
    const returned : mapPresets = {
        ASSET_SIZE : 50,
        ASSET_STEP_SIZE: 10,
        PRIMARY_SCROLL_KEY : 'Shift',
        SECONDARY_SCROLL_KEY : 'Alt',
        DISABLE_MINI_MAP_KEY : 'Control',
        START_MEASURE_KEY: 'r',
        STOP_MEASURE_KEY: 't',
        MINI_MAP_HEIGHT_PERCENT: 20,
        MINI_MAP_WIDTH_PERCENT: 20,
        MAP_WIDTH_PERCENT: 55,
        MAP_HEIGHT_PERCENT: 60,
        MAP_BORDER_LENGTH: 100,
        SCROLLING_SPEED: 20,
        SCROLLING_BOOSTER: 30,
        SCROLL_MOUSE_POSITION_THRESHOLD: 0.1,
        POSITION_X_ON_CANVAS: 0,
        POSITION_Y_ON_CANVAS: 0,
        MAP_BORDER_COLOR: 'gray',
        BORDER_GRAPHIC_URL: '',
        ASSET_ACTIVE_STROKE_STYLE: 'blue',
        ASSET_ACTIVE_LINE_WIDTH: 3,
        ASSET_ACTIVE_SHADOW_FILL_STYLE: 'gray',
        PLACEHOLDER_TEXT: 'Map is loading...',
        PLAHOLDER_FILL_STYLE: 'white',
        PLACEHOLDER_TEXT_SIZE_PERCENT: 10,
        PLACEHOLDER_TEXT_ALIGNMENT: 'center',
        PLACEHOLDER_FONT: 'Fondamento',
        DISTANCE_TEXT_SIZE_PERCENT: 5,
        MINI_MAP_RIGHT_MARGIN_PERCENT: 5,
        MINI_MAP_BOTTOM_MARGIN_PERCENT: 5,
        MINI_MAP_BORDER_THICKNESS: 4,
        MINI_MAP_BORDER_STROKE_STYLE: 'black',
        MINI_MAP_POINTER_FILL_STYLE: 'gray',
        MINI_MAP_PREVIEW_STROKE_STYLE: 'red',
        MINI_MAP_PREVIEW_LINE_WIDTH: 2,
        FEET_DISTANCE_MULTIPLIER: 5,
        DISTANCE_FONT: 'Laila',
        DISTANCE_FONT_SIZE_PERCENT: 3,
        DISTANCE_LINE_COLOR: 'white',
        DISTANCE_CIRCLE_FILL_STYLE: 'rgba(80, 80, 80, 0.5)',
        DISTANCE_LINE_WIDTH_PERCENT: 10,
        DISTANCE_FONT_FILL_STYLE: 'white',
        DISTANCE_OVERFLOWING_FONT_FILL_STYLE: '#771a0e',
        DISTANCE_OVERFLOWING_FONT_STROKE_STYLE: 'white',
        DISTANCE_OVERFLOWING_LINE_COLOR: '#771a0e',
        DISTANCE_FONT_STROKE_STYLE: 'black',
        MINI_MAP_HIDE_FILTER_TIME: 500,
        PING_TIME_MILISECONDS: 5000,
        PING_MINIMAL_RADIUS: 20,
        PING_MAXIMAL_RADIUS: 100,
        PING_INCREASE_RADIUS: 10,
        PING_MAX_NUMBER_OF_CYCLES: 5,
        PING_FILL_STYLE: 'rgba(0,0,0,0.4)',
        PING_MINI_MAP_COLOR: 'white',
        HP_BAR_Y: 0,
        HP_BAR_HEIGHT: 10,
        HP_BAR_BORDER_COLOR: 'black',
        HP_BAR_COLOR: '#771a0e',
        HP_BAR_EMPTY_COLOR: 'gray',
        HP_BAR_TEXT_COLOR: 'white',
        HP_BAR_FONT: '12px Laila',
        HP_BAR_BORDER_THICKNESS: 3,
        HP_BAR_TOP_MARGIN: 5,
        HP_BAR_TEXT_OFFSET_Y: 8,
        HP_BAR_WIDTH_OVERFLOW: 10,
        HP_BAR_TEXT_ALIGN: 'center',
        COORDINATES_BOX_X: 30,
        COORDINATES_BOX_Y: 60,
        COORDINATES_TEXT_FONT: '20px Laila',
        MOUSE_CLICK_TIME_FILTER: 200,
        SIZE_INCREASE_FILTER: 20,
        DRAWING_MAX_SIZE: 600,
        DRAWING_MIN_SIZE: 20,
        PREVENT_SELECTING_CHARACTERS_KEY: 'Shift',
        MAX_CONDITIONS_PER_ROW: 3,
        CONDITION_FONT: '12px Laila',
        CONDITION_GRID_GAP: 10,
        CONDITION_PADDING: 5,
        CONDITION_BORDER_WIDTH: 4,
        DISTANCE_BEFORE_CONDITION_FORCE: 5,
        CONDITIONS_MARGIN_TOP: 50,

        INITIATIVE_MAX_WIDTH_PERCENTAGE: 80,
        INITIATIVE_DECORATOR_WIDTH: 20,
        INITIATIVE_DECORATOR_HEIGHT: 35,
        INITIATIVE_PADDING: 10,
        INITIATIVE_ASSET_SIZE: 35,
        INITIATIVE_DISTANCE_BETWEEN_ASSETS: 10,
        INITIATIVE_Y_POSITION: 25
    }
    
    return returned;
}

export function getDefaultDrawing(): DrawingData{
    return{
        shapeType: '',
        color: '',
        size: 0,
        feets: '0',
        meters: '0',
        angle: 0,
        x: 0,
        y: 0
    }
}